### ISSUE TITLE
Convention global attribute should be in convention...

### ISSUE THREAD

**Issue by cbcunc** [ugrid-conventions/ugrid-conventions#11]
...and not just in the README.

**Comment by rsignell-usgs** [comment]
Actually, a more careful reading of the Unidata Conventions Page
http://www.unidata.ucar.edu/software/netcdf/conventions.html
it seems to me that we should be specifying 
```
Conventions = "CF-1.6/UGRID-0.9"
```
because we are specifying *additional* conventions, not independent conventions.

Can you guys please read the conventions description beginning at the part
"It may be convenient for defining institutions and groups to use a hierarchical structure for general conventions and more specialized conventions...." 
and see if you agree?

**Comment by ChrisBarker-NOAA** [comment]
On Fri, Mar 13, 2015 at 6:02 AM, Rich Signell <notifications@github.com>
wrote:

> Actually, a more careful reading of the Unidata Conventions Page
> http://www.unidata.ucar.edu/software/netcdf/conventions.html
> it seems to me that we should be specifying
>
> Conventions = "CF-1.6/UGRID-0.9"
>
> because we are specifying *additional* conventions, not independent
> conventions.
>
> Can you guys please read the conventions description beginning at the part
> "It may be convenient for defining institutions and groups to use a
> hierarchical structure for general conventions and more specialized
> conventions...."
> and see if you agree?
>
I see this:
"""
some additional conventions for a specific subset of XXX data...and files
that adhered to these additional conventions would use the global attribute

    :Conventions = "XXX/Time_series" ;

"""

and:

"""
It is possible for a netCDF file to adhere to more than one set of
conventions, even when there is no inheritance relationship among the
conventions.
"""

We've been talking, from the beginning that UGRID is an extension of CF --
so teh the former, and Rich is right.

So I guess the question is -- could someone create a dataset that conforms
to UGRID (has the grid specifications right) but not be otherwise CF
compliant (doesn't have other things CF requires)? My thought is to
disallow that -- it's not UGRID if it's not CF, in which case, we have an
inheritance relationship.

But one could argue that there's not reason to not use UGRID by itself, if
someone has reason to, in which case we have independent conventions -- can
anyone see a use case (other than lazyness) for that? Maybe someone wants
to use a non-CF compatible convention for other aspects of the data?

In practice, this probably makes very little difference -- I"d probably
write the code:

if "UGRID" in conventions:
    .....

anywya, so whther there is a slash, or a space, or a comma wouldn't make a
difference.

Also _ I suppose a CF and UGRID compliant dataset could do:

"CF-1.6/UGRID-0.9"

whereas something else could do:

"Some_other_convention, UGRID-0.9"

and we'd all be happy.

So I'm not sure we need to specify this in the convension, but rather in
implimentation -- i.e. py_ugrid might want to use:

"CF-1.6/UGRID-0.9"

even if we don't enforce that in the convention.

-Chris



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by rsignell-usgs** [comment]
@ChrisBarker-NOAA ,yes, that's what I'm talking about.

**Comment by cbcunc** [comment]
In one place the UGRID convention reads "we start from the Climate & Forecast (CF) Metadata Conventions." In the UGRID README is states "NetCDF files using this convention can be be given the global attribute Conventions = 'UGRID-0.9'," which looks more standalone. But the intention is to propose a CF extension, In which case I think the inheritance / additional convention / forward slash notion is correct.

I think there is language in UGRID that implies it is not independent of CF:

"The CF conventions allow you to provide the geospatial and temporal coordinates for scientific data, but currently assumes that the horizontal topology may be inferred from the i,j indices of structured grids. This proposal <strong>adds conventions</strong> for specifying the topology for unstructured (e.g. triangular) grids."

Using the word "adds" implies that UGRID adds to CF, that is is an additional convention and not independent. So I think the UGRID document should be updated to read that the Conventions attribute should be "CF-1.6/UGRID-0.9" and any compliance checkers should look for that even if application code checks only for UGRID in Conventions.

An independent convention could then be used with UGRID as:

"some_other_convention CF-1.6/UGRID-0.0"

Another nasty is that the actual CF convention document at http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#idp4625472 rather than the Unidata NUG Rich quotes specifies spaces around CF-1.6 like this:

" CF-1.6 "

But I don't believe anybody does that in real life. It's not consistent with the NUG and CF states that it is built on and deferd to the NUG, even though it also claims it could be implemented in file formats other than NetCDF. And it's just silly. The CF convention document needs this edited? Do compliance checkers bark on this?

**Comment by ChrisBarker-NOAA** [comment]
@cbcunc: yeah, we've always had it in mind that this was an extension to CF, in which case the slash does seem to be the way to go.

I'm just wondering out loud if there is any reason to make that restriction -- though I dont personally have a use-case.

"""
An independent convention could then be used with UGRID as:
"some_other_convention CF-1.6/UGRID-0.0"
"""

which would only be correct if the other conversion was CF- compatible. I'm suggesting that it wouldn't necessarily be so.

But again, I dont have a use-case, so probaly it makes sense to keep it simple and call this the:

CF-1.6/UGRID-x.y

convention. As you say -- it's in keeping with all the docs so far.

**Comment by rsignell-usgs** [comment]
Perhaps I led us on a wild goose chase here.   Bottom line is that applications that are `UGRID-0.9` compliant will search the `Conventions` for `UGRID-x.y.z` and be happy if `UGRID` is found and version numbers are high enough.   It won't care if there are '/' or ',' or ' ', or combinations thereof.

**Comment by cbcunc** [comment]
Yes. that's good enough for applications. The UGRID spec, though, should probably say "CF-1.6/UGRID-0.9" because the NetCDF should also be usable by applications that are only concerned with CF and are UGRID-unaware. If all those applications see is "UGRID-0.9" then UGRID-unaware applications might believe such NetCDF aren't CF. We need <em>something</em> in the UGRID spec (and not just the README) about the Conventions attribute. So it should be something that pleases all the use cases. You made a good catch finding in the NUG how extensions should be handled.

**Comment by hrajagers** [comment]
Hi, it seems that you have already figured out a pragmatic way forward. I
agree with much what was written. I just wanted to mention two use cases
that may be UGRID compliant but not CF compliant:

1. a grid with local coordinates only (i.e. no latitude and longitude).
This could a simple theoretical test model which bears no reference to any
place on earth.

2. a file in which to save space only UGRID is used to specify the location
of data and not the CF equivalent auxiliary coordinates and associated
bounds are specified. I hope that some day in the future mesh/location will
be an acceptable equivalent to the auxiliary coordinates in some CF-x.y
version.

Best regards,

Bert
Op 13 mrt. 2015 21:47 schreef "Rich Signell" <notifications@github.com>:

**Comment by rsignell-usgs** [comment]
Thanks Bert.  I think we have a concensus.    We should write:
```
Conventions = 'CF-1.6, UGRID-0.9"
```
If the files are both `CF-1.6` and `UGRID-0.9` compliant, and 
```
Conventions = `UGRID-0.9`
```
if they are not.     Okay to close this?

**Comment by cbcunc** [comment]
Argh. This seems wrong to me. If UGRID is going to be a CF extension, then it needs to be CF-compliant itself. I don't think that applies to use cases (like non-earth) that aren't CF-compliant.  If mesh can substitute for auxiliary coordinates, then that needs to be a part of the proposal. But it seems like a proposal that would break backward compatibility for UGRID with CF, so it seems like a use case that shouldn't be covered. This got closed faster than I could respond. I still think "CF-1.6/UGRID-0.9" is the only consistently correct form.

**Comment by ChrisBarker-NOAA** [comment]
On Mon, Mar 16, 2015 at 8:48 AM, Chris Calloway <notifications@github.com>
wrote:

> Argh. This seems wrong to me. If UGRID is going to be a CF extension, then
> it needs to be CF-compliant itself. I don't think that applies to use cases
> (like non-earth) that aren't CF-compliant. If mesh can substitute for
> auxiliary coordinates, then that needs to be a part of the proposal. But it
> seems like a proposal that would break backward compatibility for UGRID
> with CF, so it seems like a use case that shouldn't be covered. This got
> closed faster than I could respond. I still think "CF-1.6/UGRID-0.9" is the
> only consistently correct form.
>
I think the trick here is that  the concept of a "derived standard" and the
use of teh slash isn't actually broadly used. And "m not sure it's useful
at all:

If your file is compliant with CF and UGRID, you use:

"CF-1.6, UGRID-0.9"

which tells the client what it needs to tell the client.

Use of "CF-1.6/UGRID-0.9" also tells the client that, in theory, UGRID
never exists without CF, but how is that useful information?

If the UGRID standard does not, in fact exist without CF compliance, then
"UGRID-x.y" would never get used by itself, but I'm not sure that's an
important bit of information to convey in a CF+UGRID compliant file.

I think Bert's examples of non-CF UGRID use-cases are good ones. It would
be nice, then, if we could clearly define what a minimal UGRID file is, as
distinct from a UGRID-CF file. But until then, we can stick with what we've
got and recommend that:

"CF-1.6, UGRID-0.9"

be used.

BTW, has anyone tried a UGRID file against a CF compliance checker? I
wonder if it would get confused by some of the extra stuff in there...

-CHB









-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by hrajagers** [comment]
CF checkers will ignore any attributes that it doesn't know. So, mesh and
location attributes and most of the attributes on the mesh variable are
perfectly fine for CF.

However, you may typically get the following problems:

* If you not all faces have the same number of nodes, you'll need a
_FillValue for the dummy coordinates (unless you use a NetCDF4 ragged
array, which is not supported by the checker). The checker doesn't like it:

WARNING (7.1): Boundary Variable mesh2d_face_y_bnd should not have
_FillValue attribute

* The cf_role keyword is used by CF and although we have talked with
Jonathan Gregory about using cf_role = mesh_topology,
edge/face_node_connectivity, it's not an official CF accepted value. This
triggers:

ERROR (9.5): Invalid value for cf_role attribute

Practically this actually implies that at this point in time any UGRID file
cannot be CF compliant.

I was hoping that we could move forward and get UGRID as part of CF then
all would be solved. If we don't get the UGRID use of the cf_role accepted,
we have to make UGRID more independent and introduce a ugrid_role. However,
then it becomes more difficult to integrate them in the future.

Best regards,

Bert

**Comment by cbcunc** [comment]
On 3/16/2015 11:59 AM, Chris Barker wrote:
> I think the trick here is that the concept of a "derived standard" and the
> use of teh slash isn't actually broadly used. And "m not sure it's useful
> at all:

There are some newish CF extensions for things like glider tracks. And 
although you aren't seeing them broadly used *yet*, it's because the 
NOCs that want to use and developed those extensions are in development 
themselves, just like the UGRID community. But preparations are being 
made for CF extensions to become an everyday thing in met and ocean data.

> If your file is compliant with CF and UGRID, you use:
>
> "CF-1.6, UGRID-0.9"
>
> which tells the client what it needs to tell the client.

Agreed that it tells the client something.

> Use of "CF-1.6/UGRID-0.9" also tells the client that, in theory, UGRID
> never exists without CF, but how is that useful information?

It's useful in that the independent convention view of "CF-1.6, 
UGRID-0.9" implies there could be a CF-less convention of just "UGRID-0.9".

I hadn't thought that was a view we wanted to promote. I thought the 
idea was to get UGRID approved as a CF extension. I still believe that 
is the correct approach if we want UGRID to have broad use and acceptance.

However, I may be wrong in this view. Looking at this commit 23 hours ago:

https://github.com/ugrid-conventions/ugrid-conventions/commit/3e698be3058f3281c898b5081b70864d90dddc8d

I then think that CF-extension view has cracks in support.

> If the UGRID standard does not, in fact exist without CF compliance, then
> "UGRID-x.y" would never get used by itself, but I'm not sure that's an
> important bit of information to convey in a CF+UGRID compliant file.

It may not be useful to convey in a UGRID compliant file. But it is most 
important to convey in a UGRID spec. A UGRID spec that is to be 
submitted as a CF extension needs to specify the value for the 
Conventions attribute according to CF rules, which in the case of 
extensions is *clearly* distinct from additional independent conventions.

> I think Bert's examples of non-CF UGRID use-cases are good ones.

I don't look at use cases as good or bad. They are simply statements of 
what people need to do. And I believe Bert may need to satisfy the use 
cases he lists. The question is whether those use cases are a good fit 
for a spec that is designed to be submitted as a CF extension.

> It would
> be nice, then, if we could clearly define what a minimal UGRID file is, as
> distinct from a UGRID-CF file.

Is that even possible within the context of a CF extension? Is this spec 
defining two conventions? One that is a CF extension and one that is not?

> But until then, we can stick with what we've
> got and recommend that:
>
> "CF-1.6, UGRID-0.9"
>
> be used.

I'm not going to argue this anymore because it feels like lawyering, 
even thought I think it is a mistake if the goals are acceptance as a CF 
extension (for you'd want the spec to be consistent with CF rules for 
extensions) and uptake of UGRID among data producers and application 
developers as it becomes recognized as a CF extension. It was only 
important to me now because I immediately need to communicate to a 
community of modelers who are not currently UGRID compliant how they can 
get that way. I need to communicate something, so "CF-1.6, UGRID-0.9" is 
what I will communicate until I can somehow other convince anyone.

I feel like I need to communicate a Conventions attribute value today 
that is going to need to change before the spec can be submitted as a CF 
extension, which means I'll need to communicate a change in the future 
to my community of modelers, which will not bode well operationally or 
for acceptance. I'd like to head off that mistake.

> BTW, has anyone tried a UGRID file against a CF compliance checker? I
> wonder if it would get confused by some of the extra stuff in there...

Compliance checkers need to be judged by whether they correctly 
implement specs, not by whether they are confused by files that are 
correct. If it is confused by correct things, then that's what should 
get fixed.

A CF checker today *should* reject a UGRID file. UGRID is not a current 
CF extension. So I don't find it interesting if a UGRID file doesn't 
pass a CF check *today*.

But there are checkers under development that are looking to the future, 
particularly in regards to UGRID. And those checkers should be looking 
to the UGRID spec for what to expect, and in my opinion to the CF spec 
as well. So I only find it interesting to see that those forward-looking 
checkers pass a correct UGRID file and I think this issue about what's 
correct in a CF context.

Today the spec doesn't address the Conventions attribute. Only the 
README does. And the README implies two conventions, one of which 
wouldn't even need to pass a CF compliance check. (Does there need to be 
a non-CF UGRID compliance checker?)

I'd like to see the Conventions attribute in the spec and not just in 
the README. That's the issue I opened. And I think what goes in the spec 
should be what could be proposed as a CF extension. That is, if conforms 
to CF itself, including rules for extensions. Finally, I think it should 
go in the spec today in the way we expect it to be approved as an 
extension in the future, not just as a stop gap for today while it's not 
yet a CF extension.

Doing this would provide two things. One, a measure of forward-looking 
compliance checkers. And two, something to communicate to communities of 
modelers that they can rely on in the future; something that inspires 
acceptance; something with less built-in ambiguity.

-- 
Sincerely,

Chris Calloway, Applications Analyst
UNC Renaissance Computing Institute
100 Europa Drive, Suite 540, Chapel Hill, NC 27517
(919) 599-3530

**Comment by ChrisBarker-NOAA** [comment]
Just  few comments:

On Tue, Mar 17, 2015 at 8:56 AM, Chris Calloway <notifications@github.com>
wrote:

> On 3/16/2015 11:59 AM, Chris Barker wrote:
> > I think the trick here is that the concept of a "derived standard" and
> the
> > use of the slash isn't actually broadly used. And "m not sure it's useful
> > at all:
>
> There are some newish CF extensions for things like glider tracks. And
> although you aren't seeing them broadly used *yet*,


I wasn't questioning the use existence or use of CF extensions -- I was
questioning the use of the slash. My impression was that Rich talked to CF
folks, and implied that the slash isn't generally used. If is is generally
used, then I'm fine with using it. But if it's not, then client software
that looks for comma  (or space) separated conventions is going to barf on
the slash.

> If your file is compliant with CF and UGRID, you use:
> >
> > "CF-1.6, UGRID-0.9"
> >
> > which tells the client what it needs to tell the client.
>
> Agreed that it tells the client something.


I propose that it tells it all it needs to know. If a file is compliant
with two standards, then it makes no difference whether one of those is a
"sub-standard" of the other.

> Use of "CF-1.6/UGRID-0.9" also tells the client that, in theory, UGRID
> > never exists without CF, but how is that useful information?
>
> It's useful in that the independent convention view of "CF-1.6,
> UGRID-0.9" implies there could be a CF-less convention of just "UGRID-0.9".
>
> I hadn't thought that was a view we wanted to promote. I thought the
> idea was to get UGRID approved as a CF extension. I still believe that
> is the correct approach if we want UGRID to have broad use and acceptance.
>

Whether we promote that idea or not comes down to the conventions doc, NOT
the recommended conventions string. But to the extent it does, if the doc
says:

A UGRID compliant file with have the convention string:

"CF-1.6, UGRID-0.9"

Then that's a pretty strong statement that these files are both CF and
UGRID compliant.

However, I may be wrong in this view. Looking at this commit 23 hours ago:
>
>
> https://github.com/ugrid-conventions/ugrid-conventions/commit/3e698be3058f3281c898b5081b70864d90dddc8d


OK -- that does remove that statement above - but again, nothign to do with
whether we use the slash or not.

> I think Bert's examples of non-CF UGRID use-cases are good ones.
>
> I don't look at use cases as good or bad. They are simply statements of
> what people need to do.


OK -- so someone needs to express data that needs a UGRID-like standard,
that isn't CF-compliant -- I can't see any benefit to prohibiting that. (of
course we can't prohibit anything, but theoretically, we would be
prohibiting use the UGRID name as the convension -- why not?

My suggestion:

We very clearly specify that UGRID is designed to be CF compliant -- i.e.
it can be added to CF files, you will be able, and encouraged (maybe once
some extra stuff is adopted by CF) to create files compliant with both.

If, at some point, someone want to be more clear about what a non-CF
compliant UGRID file would look like, then that can be added later. I can't
see any harm in leaving that door open.

The question is whether those use cases are a good fit
> for a spec that is designed to be submitted as a CF extension.


I can't say we know that until we try -- I can't actually imagine any
reason that a CF-compatible spec couldn't simply leave a few things out
that aren't relevant to the use-case.

But I guess this is the point -- in order to be submitted as a CF
extension, it has to be CF-compatible -- I can't see any reason that it HAS
to be unusab'e witout CF? That seems like a completely worthless and
arbitrary restriction.


> Is that even possible within the context of a CF extension? Is this spec
> defining two conventions? One that is a CF extension and one that is not?


Why not? A UGRID file is "this" a UGRID_CF is "this" plus
"this_extra_stuff". And we probably don't need to specify exactly what
"this_extra_stuff" is -- that's what CF specifies.

I'm not going to argue this anymore because it feels like lawyering,
>

if we are arguing about the slash, then it is lawyering -- but it seems
there are some issues with the goal of the spec, which we should gain
consensus on.

I'm proposing that the goal of the spec is to be CF-compatible. Whether it
can be used without CF also can be left up in the air -- I can't see any
reason to put in that restriction up front.

even thought I think it is a mistake if the goals are acceptance as a CF
> extension (for you'd want the spec to be consistent with CF rules for
> extensions) and uptake of UGRID among data producers and application
> developers as it becomes recognized as a CF extension. It was only
> important to me now because I immediately need to communicate to a
> community of modelers who are not currently UGRID compliant how they can
> get that way. I need to communicate something, so "CF-1.6, UGRID-0.9" is
> what I will communicate until I can somehow other convince anyone.
>

I think that will be fine -- in fact, you want to recommend _both_ UGRID
and CF -- that's probably what you want to promote, regardless of whether
UGRID exists without CF or not.


> I feel like I need to communicate a Conventions attribute value today
> that is going to need to change before the spec can be submitted as a CF
> extension,


I got the impression the CF folks recommended the comma -- so no problem
there.

> BTW, has anyone tried a UGRID file against a CF compliance checker? I
> > wonder if it would get confused by some of the extra stuff in there...
>
> Compliance checkers need to be judged by whether they correctly
> implement specs, not by whether they are confused by files that are
> correct.


Sorry worded wrong -- the question I meant was:

Are UGRID, CF files CF compliant out of the box, or does CF need to
incorporate some changes first? The compliance checker was shorthand for
that...

A CF checker today *should* reject a UGRID file. UGRID is not a current
> CF extension. So I don't find it interesting if a UGRID file doesn't
> pass a CF check *today*.
>

But CF allows other standards -- It doesn't disallow putting whatever extra
stuff is on there, as long as that extra stuff is CF compliant. CF doesn't
have to except it as an extension for it to be CF compliant.

CF only need to accept it as an extension if we want to call it "CF-UGRID",
or somethign like that, and if we want to use a  "cf-role attribute".

Today the spec doesn't address the Conventions attribute. Only the
> README does. And the README implies two conventions, one of which
> wouldn't even need to pass a CF compliance check. (Does there need to be
> a non-CF UGRID compliance checker?)
>

If we promote a non-CF UGRID format, yes. But I don't know who's going to
write a full, both standards compliance checker anyway -- I can only image
that a UGRID checker would check the UGRID-specific stuff, and not
everything else.

I'd like to see the Conventions attribute in the spec and not just in
> the README.


 Indeed.




> That's the issue I opened. And I think what goes in the spec
> should be what could be proposed as a CF extension.


Agreed also.


> That is, if conforms
> to CF itself, including rules for extensions. Finally, I think it should
> go in the spec today in the way we expect it to be approved as an
> extension in the future, not just as a stop gap for today while it's not
> yet a CF extension.
>

Also agreed

All this points to "CF-1.6, UGRID-0.9"

Note that that slash recommendation comes from Unidata -- NOT CF:

http://www.unidata.ucar.edu/software/netcdf/conventions.html

Interestingly, CF says:
"""
Files that conform to the CF version 1.5 conventions must indicate this by
setting the global Conventions attribute to the string value "CF-1.5".
"""
from:
http://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.7.html

With no mention of how to add other conventions

There is also this:

"""
We recommend that netCDF files that follow these conventions indicate this
by setting the NUG defined global attribute Conventions to the string value
"CF-1.7" . The string is interpreted as a directory name relative to a
directory that is a repository of documents describing sets of
discipline-specific conventions. The conventions directory name is
currently interpreted relative to the directory pub/netcdf/Conventions/ on
the host machine ftp.unidata.ucar.edu. The web based versions of this
document are linked from the netCDF Conventions web page .
"""

That explains the slash -- but also implies that we can't / shouldn't use
the slash unless it's a convention hosted by Unidata (kind of weird,
actually). But again, I understand conceptually the distinction between a
convention that inherits from CF and one that does not, but see no reason
that that needs to be made clear in the conventions string.


-CHB


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by rsignell-usgs** [comment]
I'm glad you guys pulled on this a bit to see if it snapped back.  Looks like it did.
